NeoTech-Software/Abysner

gradle/libs.versions.toml

This is mainly to keep it in line with the compose std libraries currently used. This also fixes a desktop (preview) rendering issue.

Update: Compose plugin to alpha version

---

composeApp/build.gradle.kts

**Compared to release 1.0.0-alpha(01):**
- Added: Cylinder planning
- Changed: warnings and critical warnings are displayed a bit nicer
- Added: Option to share plan as image

Release: 1.0.0-alpha02

---

composeApp/build.gradle.kts
iosApp/iosApp/Info.plist

Apple does not allow the usage of 'alpha' in the app version, thus we have to use the patch section of the app version. So to keep things consistent I'm also changing this for Android.

Release: 1.0.1-alpha

---

domain/src/commonMain/kotlin/org/neotech/app/abysner/domain/gasplanning/GasPlanner.kt
domain/src/commonTest/kotlin/org/neotech/app/abysner/domain/gasplanning/GasPlannerTest.kt

This down the line lead to a crash in the gas pie chart, as it was expecting the out-of-air scenario cylinder statistics to be (always) available.

Fix: Gas planner unable to find worst-case scenario's

---

composeApp/build.gradle.kts
iosApp/iosApp/Info.plist

Fixes only a crash when planning multi-level dives, no new features.

Release: 1.0.2-alpha

---

composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/decoplan/GasPieChart.kt

Should there be no 'extra gas required' information, then this helps to better display the graph and legend.

Change: Make sure the legend for the gas usage pie chart is automatically adjusted

---

composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/component/GasDisplay.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/ShareImage.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/decoplan/DecoPlanCard.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/gasplan/GasPlanCard.kt

This also changes the CNS and OTU display in shared images (most notably the font size has slightly decreased).
Fixes: #11

Change: Show CNS and OTU values a bit more pronounced in the deco plan

---

composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/component/BigNumberDisplay.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/component/GasPropertiesComponent.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/component/SegmentedButtonRowComponent.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/PlanScreen.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/cylinders/CylinderPickerBottomSheet.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/segments/SegmentPickerBottomSheet.kt

When selecting a cylinder only the deco MOD was being shown, while it is not yet clear what this cylinder is going to be used for. So instead as kinda of a quick fix, the app now shows both MODs.
This also improves the gas properties display a bit, especially on smaller screens.
Fixes: #23

Fix: Show both normal and deco PPO2 MOD

---

composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/component/MultiChoiceSegmentedButtonRowComponent.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/component/SingleChoiceSegmentedButtonRowComponent.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/preview/PreviewData.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/ConfigurationSummeryDialog.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/PlanScreen.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/PlanScreenViewModel.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/decoplan/DecoPlanCard.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/decoplan/DecoPlanGraph.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/decoplan/GasPieChart.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/gasplan/GasPlanCard.kt
domain/src/commonMain/kotlin/org/neotech/app/abysner/domain/diveplanning/model/DivePlanSet.kt

Instead of calculating 2 plans: 'base' and 'contingency' (a plan that is both deeper and longer). Now only 1 plan is calculated, this plan can however be adjusted by the user: the user can choose to either make the plan deeper or longer or both.
Now that there is essentially 1 plan (that may or may not be adjusted), the gas plan makes a bit more sense: as it always shows the amount of gas you need for this 1 plan (adjusted for deeper, longer, or both). The gas plan used to be always based on the deeper and longer plan, which could be confusing to users.

Refactor: Contingency planning

---

composeApp/src/androidMain/kotlin/org/neotech/app/abysner/presentation/utilities/ShareExtensions.android.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/utilities/ComposeImageExtensions.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/utilities/ShareExtensions.kt
composeApp/src/desktopMain/kotlin/org/neotech/app/abysner/presentation/utilities/ShareExtensions.desktop.kt
composeApp/src/iosMain/kotlin/org/neotech/app/abysner/presentation/utilities/ShareExtensions.ios.kt

This mostly seems to improve sharing on iOS (since the ViewController is now also created on the background dispatcher)

Refactor: offload bitmap and file handling to a background dispatcher

---

composeApp/build.gradle.kts
iosApp/iosApp/Info.plist

- Changed: SAC rate is now increased to 20 l/min (#6)
- Changed: Contingency planning is now more flexible (#35)
- Contingency plan can be chosen as a combination added depth, and/or added time.
- Gas plan is now based on selected contingency options.
- Changed: CNS and OTU values displayed with more emphasis (#11)
- New: Option to easily pick standard gases (#8)
- New: Planned dive is now persisted (#2)
- New: 'Travel time' hint when editing a dive segment (#9)
- Fixed: Cylinder/gas picker now shows both deco and non-deco PPO2 (#23)
- Fixed: Cylinder dropdown showing all cylinders as the same size (#26)
- Improved: Empty cylinder alert and warning colors (#28)
- Improved: Share performance (#37)

Release: 1.0.3-alpha

---

composeApp/build.gradle.kts
iosApp/iosApp/Info.plist

This release does not contain any changes (compared to 1.0.3-alpha), except for dependency updates.

Release: 1.0.4-beta

---

composeApp/build.gradle.kts
iosApp/iosApp/Info.plist

- Fixed: Tables showing old data #52 
- Fixed: Image share on iOS sometimes not working #51 
- Fixed: Typo in the about screen #50

Release: 1.0.5-beta

---

composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/component/TextAlertComponent.kt

This seems to happen if the text does not fit to begin with, then it is hard to figure out what the bounding box would be.

Fix: Crash in TextAlert when text size is too big

---

composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/decoplan/DecoPlanCard.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/decoplan/GasPieChart.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/gasplan/GasPlanCard.kt
domain/src/commonMain/kotlin/org/neotech/app/abysner/domain/gasplanning/GasPlanner.kt
domain/src/commonMain/kotlin/org/neotech/app/abysner/domain/gasplanning/model/GasPlan.kt
domain/src/commonMain/kotlin/org/neotech/app/abysner/domain/gasplanning/model/GasUsage.kt
domain/src/commonTest/kotlin/org/neotech/app/abysner/domain/gasplanning/GasPlannerTest.kt

This was caused by (wrongly) assuming 2 sorted lists were sorted exactly the same (by cylinder). This commit fixes the bug but also avoids working with multiple lists in the first place to hopefully avoid confusion in the future.
Fixes #59

Fix: Incorrect numbers displayed for cylinder pressures

---

composeApp/build.gradle.kts
iosApp/iosApp/Info.plist

This release makes a major change to the way the gas plan is presented, the pie chart is gone and a new bar chart takes its place. All details related to this change can be found in this PR: #65. Other then these changes no things have changed since release 1.0.6-beta.

Release: 1.0.7-beta

---

domain/src/commonMain/kotlin/org/neotech/app/abysner/domain/core/model/Gas.kt

Nitrox 28 (EAN28) is a commonly used gas mix, suitable for both recreational and technical diving. It allows for a deeper dives, such as those approaching 40m, while still reducing nitrogen absorption compared to air. This commit adds support for Nitrox28 in gas.kt model to reflect its practical use.

Add: Nitrox 28% as standard gas

---

buildSrc/src/main/kotlin/abysner.jacoco-conventions.gradle.kts
buildSrc/src/main/kotlin/org/neotech/gradle/GradleUtilities.kt
composeApp/build.gradle.kts
data/build.gradle.kts
domain/src/commonMain/kotlin/org/neotech/app/abysner/domain/core/model/Gas.kt
domain/src/commonMain/kotlin/org/neotech/app/abysner/domain/core/physics/Pressure.kt
domain/src/commonMain/kotlin/org/neotech/app/abysner/domain/decompression/DecompressionPlanner.kt
domain/src/commonMain/kotlin/org/neotech/app/abysner/domain/decompression/algorithm/DecompressionModel.kt
domain/src/commonMain/kotlin/org/neotech/app/abysner/domain/decompression/algorithm/buhlmann/Buhlmann.kt
domain/src/commonMain/kotlin/org/neotech/app/abysner/domain/decompression/algorithm/buhlmann/BuhlmannUtilities.kt
domain/src/commonMain/kotlin/org/neotech/app/abysner/domain/diveplanning/model/DivePlan.kt
domain/src/commonMain/kotlin/org/neotech/app/abysner/domain/gasplanning/GasPlanner.kt
domain/src/commonMain/kotlin/org/neotech/app/abysner/domain/gasplanning/OxygenToxicityCalculator.kt
domain/src/commonTest/kotlin/org/neotech/app/abysner/domain/core/physics/PressureTest.kt

This does a few things: avoids many conversions between pressure in bar and depth in meters (better performance), aids in supporting both metric and imperial units in the future, prepares for other feature like planning multiple dives and adding surface intervals.
Functionally nothing has changed, results remain the same.

Refactor: Use pressure instead of length units for depth in internals

---

composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/component/BigNumberDisplay.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/component/GasPickerComponent.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/component/GasPropertiesComponent.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/component/MultiChoiceSegmentedButtonRowComponent.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/component/SingleChoiceSegmentedButtonRowComponent.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/component/TextAlertComponent.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/component/graphs/HorizontalGraphAxis.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/AboutScreen.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/ShareImage.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/PlanScreen.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/cylinders/CylinderPickerBottomSheet.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/cylinders/CylindersCard.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/decoplan/DecoPlanCard.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/decoplan/DecoPlanGraph.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/gasplan/GasBarChart.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/gasplan/GasPlanCard.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/gasplan/GasUsageDetailsDialog.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/segments/SegmentPickerBottomSheet.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/planner/segments/SegmentsCard.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/screens/terms_and_conditions/TermsAndConditionsScreen.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/theme/Theme.kt
composeApp/src/commonMain/kotlin/org/neotech/app/abysner/presentation/utilities/PreviewWrapper.kt

Newer Android Studio versions support previews in commonMain, without workarounds using desktop preview annotations, the code now uses `org.jetbrains.compose.ui.tooling.preview.Preview` for annotating previews.

Remove: Compose preview workaround in commonMain sources

---

.gitignore
composeApp/build.gradle.kts
gradle/libs.versions.toml
iosApp/iosApp/Info.plist

This is a maintenance release. It contains mostly dependency updates and internal refactoring for upcoming features. In addition, it includes a few small feature changes, such as a higher default GF-low value and the addition of Nitrox 28 as a standard gas.

Release: 1.0.8-beta
